[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
dynamic_padding = true

decorations = "None"
opacity = 0.95
blur = false

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"
size = 14

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
